/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospita.management.system;

/**
 *
 * @author Ashok
 */
public class display extends javax.swing.JFrame {

    /**
     * Creates new form display
     */
    public display() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        year1 = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        reason = new javax.swing.JTextArea();
        general = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        date2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        year2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        back = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        month2 = new com.toedter.calendar.JMonthChooser();
        month = new com.toedter.calendar.JMonthChooser();
        month1 = new com.toedter.calendar.JMonthChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("patient details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 10, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("ADMIT DATE:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 420, 110, 19);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setText("NAME:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 90, 60, 19);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setText("D.O.B:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 150, 60, 19);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("SEX:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 200, 60, 19);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setText("ADDRESS:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 260, 80, 19);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setText("CONTACT:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 350, 80, 19);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setText("E-MAIL:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(460, 350, 80, 19);

        email.setEditable(false);
        jPanel1.add(email);
        email.setBounds(530, 340, 220, 30);

        year.setEditable(false);
        jPanel1.add(year);
        year.setBounds(490, 140, 70, 30);

        date.setEditable(false);
        jPanel1.add(date);
        date.setBounds(250, 140, 50, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("/");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(470, 140, 10, 30);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel10.setText("/");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(310, 140, 10, 30);

        date1.setEditable(false);
        jPanel1.add(date1);
        date1.setBounds(250, 410, 50, 30);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel11.setText("/");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(310, 410, 10, 30);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel12.setText("/");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(470, 410, 10, 30);

        year1.setEditable(false);
        jPanel1.add(year1);
        year1.setBounds(490, 410, 70, 30);

        name.setEditable(false);
        jPanel1.add(name);
        name.setBounds(250, 80, 400, 30);

        reason.setEditable(false);
        reason.setColumns(20);
        reason.setRows(5);
        jScrollPane1.setViewportView(reason);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 530, 280, 100);

        general.setEditable(false);
        jPanel1.add(general);
        general.setBounds(250, 190, 140, 30);

        contact.setEditable(false);
        jPanel1.add(contact);
        contact.setBounds(250, 340, 200, 30);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel13.setText("REASON:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 540, 150, 19);

        date2.setEditable(false);
        jPanel1.add(date2);
        date2.setBounds(250, 470, 50, 30);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel14.setText("/");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(310, 470, 10, 30);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel15.setText("/");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(470, 470, 10, 30);

        year2.setEditable(false);
        jPanel1.add(year2);
        year2.setBounds(490, 470, 70, 30);

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel16.setText("DISCHARGE DATE:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 480, 150, 19);

        address.setEditable(false);
        address.setColumns(20);
        address.setRows(5);
        jScrollPane2.setViewportView(address);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(250, 240, 280, 80);

        back.setText("< BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(583, 583, 150, 40);

        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(580, 530, 150, 40);

        month2.setEnabled(false);
        jPanel1.add(month2);
        month2.setBounds(330, 470, 130, 30);

        month.setEnabled(false);
        jPanel1.add(month);
        month.setBounds(330, 140, 130, 30);

        month1.setEnabled(false);
        jPanel1.add(month1);
        month1.setBounds(330, 410, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        login l=new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        patientdetail s=new patientdetail();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea address;
    private javax.swing.JButton back;
    public static javax.swing.JTextField contact;
    public static javax.swing.JTextField date;
    public static javax.swing.JTextField date1;
    public static javax.swing.JTextField date2;
    public static javax.swing.JTextField email;
    public static javax.swing.JTextField general;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logout;
    public static com.toedter.calendar.JMonthChooser month;
    public static com.toedter.calendar.JMonthChooser month1;
    public static com.toedter.calendar.JMonthChooser month2;
    public static javax.swing.JTextField name;
    public static javax.swing.JTextArea reason;
    public static javax.swing.JTextField year;
    public static javax.swing.JTextField year1;
    public static javax.swing.JTextField year2;
    // End of variables declaration//GEN-END:variables
}
