/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospita.management.system;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashok
 */
public class patientdetail extends javax.swing.JFrame{

    /**
     * Creates new form patientdetail
     */
    public patientdetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JComboBox<>();
        month = new com.toedter.calendar.JMonthChooser();
        year = new com.toedter.calendar.JYearChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("NAME:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 120, 140, 30);

        jlabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlabel4.setText("DATE OF BIRTH:");
        jPanel1.add(jlabel4);
        jlabel4.setBounds(20, 200, 150, 30);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(190, 120, 220, 30);

        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel);
        cancel.setBounds(320, 290, 90, 30);

        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(190, 293, 90, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("ENTER DETAILS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 50, 140, 21);

        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(date);
        date.setBounds(190, 200, 50, 30);
        jPanel1.add(month);
        month.setBounds(250, 200, 94, 30);
        jPanel1.add(year);
        year.setBounds(350, 200, 77, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        option c=new option();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String s1=name.getText();
        String s2=date.getSelectedItem().toString();
        int s3=month.getMonth();
        int s4=year.getYear();
        display d=new display();
        boolean flag = false;
                    try
                    {
                       Class.forName("com.mysql.jdbc.Driver");
                       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
                       Statement stmt=con.createStatement();
                       String query="select * from register where name='"+s1+"' and DOB_date='"+s2+"' and DOB_month='"+s3+"' and DOB_year='"+s4+"'";
                       ResultSet rs=stmt.executeQuery(query);
                        if(rs.next())
                       {
                           flag = true;
                           JOptionPane.showMessageDialog(null,"record found");
                           display g=new display();
                           g.setVisible(true);
                           this.dispose();
                           String query1="select * from register where name='"+s1+"' and DOB_date='"+s2+"' and DOB_month='"+s3+"' and DOB_year='"+s4+"'";
                           ResultSet rs1=stmt.executeQuery(query1);
                        while(rs1.next())
                        {
                            System.out.println(rs1.getString(1));
                            display.name.setText(rs1.getString(1));
                            System.out.println(rs1.getString(2));
                            display.date.setText(rs1.getString(2));
                            System.out.println(rs1.getInt(3));
                            display.month.setMonth(rs1.getInt(3));
                            System.out.println(rs1.getString(4));
                            display.year.setText(rs1.getString(4));
                            System.out.println(rs1.getString(5));
                            display.general.setText(rs1.getString(5));
                            System.out.println(rs1.getString(6));
                            display.address.setText(rs1.getString(6));
                            System.out.println(rs1.getString(7));
                            display.contact.setText(rs1.getString(7));
                            System.out.println(rs1.getString(8));
                            display.email.setText(rs1.getString(8));
                            System.out.println(rs1.getString(9));
                            display.date1.setText(rs1.getString(9));
                            System.out.println(rs1.getInt(10));
                            display.month1.setMonth(rs1.getInt(10));
                            System.out.println(rs1.getString(11));
                            display.year1.setText(rs1.getString(11));
                            System.out.println(rs1.getString(12));
                            display.date2.setText(rs1.getString(12));
                            System.out.println(rs1.getInt(13));
                            display.month2.setMonth(rs1.getInt(13));
                            System.out.println(rs1.getString(14));
                            display.year2.setText(rs1.getString(14));
                            System.out.println(rs1.getString(15));
                            display.reason.setText(rs1.getString(15));
                        }
                       }
                        else{
                            JOptionPane.showMessageDialog(null, "no records found");
                        }
                    }
                    catch(Exception ex)
                      {
                      }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientdetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel4;
    private com.toedter.calendar.JMonthChooser month;
    private javax.swing.JTextField name;
    private javax.swing.JButton search;
    private com.toedter.calendar.JYearChooser year;
    // End of variables declaration//GEN-END:variables
}
