/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospita.management.system;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Selva
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        general = new javax.swing.JComboBox<>();
        date = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        date2 = new javax.swing.JComboBox<>();
        month1 = new com.toedter.calendar.JMonthChooser();
        year = new com.toedter.calendar.JYearChooser();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        month = new com.toedter.calendar.JMonthChooser();
        year1 = new com.toedter.calendar.JYearChooser();
        jLabel9 = new javax.swing.JLabel();
        date1 = new javax.swing.JComboBox<>();
        month2 = new com.toedter.calendar.JMonthChooser();
        year2 = new com.toedter.calendar.JYearChooser();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reason = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRATION FORM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 0, 300, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NAME:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 100, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("D.O.B:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 210, 50, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("SEX:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 310, 29, 17);
        jPanel1.add(name);
        name.setBounds(120, 90, 240, 40);

        general.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        general.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female", "others" }));
        jPanel1.add(general);
        general.setBounds(130, 300, 120, 30);

        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(date);
        date.setBounds(120, 210, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("ADDRESS:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 390, 70, 17);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 390, 250, 96);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("contact:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(410, 110, 60, 17);

        contact.setText("+91");
        jPanel1.add(contact);
        contact.setBounds(470, 110, 230, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("E-MAIL:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 220, 50, 20);
        jPanel1.add(email);
        email.setBounds(480, 210, 220, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("REASON:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(390, 390, 60, 17);

        date2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(date2);
        date2.setBounds(480, 320, 50, 30);
        jPanel1.add(month1);
        month1.setBounds(540, 270, 94, 30);
        jPanel1.add(year);
        year.setBounds(280, 210, 77, 30);

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(450, 480, 120, 50);

        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel);
        cancel.setBounds(600, 480, 120, 50);
        jPanel1.add(month);
        month.setBounds(180, 210, 94, 30);
        jPanel1.add(year1);
        year1.setBounds(640, 270, 77, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("ADMIT DATE:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(390, 280, 90, 17);

        date1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(date1);
        date1.setBounds(480, 270, 50, 30);
        jPanel1.add(month2);
        month2.setBounds(540, 320, 94, 30);
        jPanel1.add(year2);
        year2.setBounds(640, 320, 77, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("DISCHARGE DATE:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 330, 120, 17);

        reason.setColumns(20);
        reason.setRows(5);
        jScrollPane2.setViewportView(reason);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(460, 380, 260, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String s1 = name.getText();
        String s2 = date.getSelectedItem().toString();
        int s3 = month.getMonth();
        int s4 = year.getYear();
        String s5 = general.getSelectedItem().toString();
        String s6 = address.getText();
        String s7 = contact.getText();
        String s8 = email.getText();
        String s9 = date1.getSelectedItem().toString();
        int s10 = month1.getMonth();
        int s11 = year1.getYear();
        String s12=date2.getSelectedItem().toString();
        int s13=month2.getMonth();
        int s14=year2.getYear();
        String s15=reason.getText();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "root");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("insert into register values('" + s1 + "','" + s2 + "','" + s3 + "','" + s4 + "','" + s5 + "','" + s6 + "','" + s7 + "','"+s8+"','"+s9+"','"+s10+"','"+s11+"','"+s12+"','"+s13+"','"+s14+"','"+s15+"')");
            JOptionPane.showMessageDialog(null, "created successfully");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "failed");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        option b = new option();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField contact;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JComboBox<String> date1;
    private javax.swing.JComboBox<String> date2;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> general;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JMonthChooser month;
    private com.toedter.calendar.JMonthChooser month1;
    private com.toedter.calendar.JMonthChooser month2;
    private javax.swing.JTextField name;
    private javax.swing.JTextArea reason;
    private javax.swing.JButton save;
    private com.toedter.calendar.JYearChooser year;
    private com.toedter.calendar.JYearChooser year1;
    private com.toedter.calendar.JYearChooser year2;
    // End of variables declaration//GEN-END:variables
}
